### PR TITLE
Remove content tables and update tutorial files

### PR DESCRIPTION
**Pull request by luseverin**
In relation to #862 and associated PR #872, this PR removes content tables from CLIMADA tutorials.
 Changes proposed in this PR:
- Remove the table of contents on top of each tutorial file
- 

This PR fixes #862.

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Descriptive pull request title added
- [ ] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_petals/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html#Static-Code-Analysis

### CODE REVIEW

**Comment by luseverin** [comment]
Following our discussion on https://github.com/CLIMADA-project/climada_python/pull/872

> I had a brief check at the other tutorials and I also noted that some cells are failing to run in the climada_hazard_entity_Crop.ipynb. Are you aware of this?
I just wanted to point out the errors in the` climada_hazard_entity_Crop.ipynb` tutorial. Should I open an issue for this?

**Comment by chahank** [comment]
> Following our discussion on [CLIMADA-project/climada_python#872](https://github.com/CLIMADA-project/climada_python/pull/872)
> 
> > I had a brief check at the other tutorials and I also noted that some cells are failing to run in the climada_hazard_entity_Crop.ipynb. Are you aware of this?
> 
> I just wanted to point out the errors in the` climada_hazard_entity_Crop.ipynb` tutorial. Should I open an issue for this?

Can you directly see why? If yes, maybe we can fix it. If not, yes please open an issue. Thanks!

**Comment by chahank** [comment]
Thanks @luseverin . It seems though that it did not yield the desired result for the [open street map tutorial](https://climada-petals--125.org.readthedocs.build/en/125/tutorial/climada_exposures_openstreetmap.html) and the [river flood tutorial](https://climada-petals--125.org.readthedocs.build/en/125/tutorial/climada_hazard_RiverFlood.html).

**Comment by luseverin** [comment]
Oh ok it seems that some garbage output from when I re rendered the notebook was included in the commit. @chahank you are referring to this, right? If yes, I will remove this from the commit.

**Comment by chahank** [comment]
hmmm maybe? I am mostly referring to the fact that the table of contents for these two tutorials is not correct.

**Comment by luseverin** [comment]
So I have removed the "outline" and "how is this tutorial structured" parts in https://github.com/CLIMADA-project/climada_petals/blob/develop/doc/tutorial/climada_exposures_openstreetmap.ipynb and https://github.com/CLIMADA-project/climada_petals/blob/develop/doc/tutorial/climada_hazard_RiverFlood.ipynb respectively. Isn't it what I was supposed to do?

**Comment by luseverin** [comment]
Ok so I have fixed the broken headers in the [open street map tutorial](https://climada-petals--125.org.readthedocs.build/en/125/tutorial/climada_exposures_openstreetmap.html) and the [river flood tutorial](https://climada-petals--125.org.readthedocs.build/en/125/tutorial/climada_hazard_RiverFlood.html). It seems to be working fine now, eventhough some of the lower-level headers in [open street map tutorial](https://climada-petals--125.org.readthedocs.build/en/125/tutorial/climada_exposures_openstreetmap.html) are not appearing on the menu on the right..

Regarding the [crop yield tutorial](https://climada-petals.readthedocs.io/en/latest/tutorial/climada_hazard_entity_Crop.html) I do not manage to run the tutorial's notebook and do not know where the errors are coming from. There also seems to be a FIleNotFoundError.. I will raise an issue about this. Maybe someone who knows this module better can fix it..

**Pull request merged**
