### PR TITLE
tc_rainfield: tests for tracks crossing the antimeridian

### PR DESCRIPTION
**Pull request by tovogt**
Changes proposed in this PR:
- Modify `TCRain` so that it profits from the fix of `TropCyclone` proposed in https://github.com/CLIMADA-project/climada_python/pull/839 This PR is also necessary for compatibility with the changes proposed there!
- Fix the values in the `TCSurgeBathtub` unit tests to be compatible with the changes in [climada_python#833](https://github.com/CLIMADA-project/climada_python/pull/833).
- Implement new unit tests for `TCRain` and `TCSurgeBathtub` to cover the case where a TC track crosses the antimeridian to prevent issues like [climada_python#831](https://github.com/CLIMADA-project/climada_python/issues/831) in the future.

### PR Author Checklist

- [x] Read the [Contribution Guide][contrib]
- [x] Correct target branch selected (if unsure, select `develop`)
- [x] Descriptive pull request title added
- [x] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#Commenting-&-Documenting) updated
- [x] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [x] [Changelog](https://github.com/CLIMADA-project/climada_petals/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html#Static-Code-Analysis

### CODE REVIEW

**Comment by peanutfun** [comment]
I can confirm this works with the current changes in https://github.com/CLIMADA-project/climada_python/pull/839

**Comment by peanutfun** [comment]
After merging https://github.com/CLIMADA-project/climada_python/pull/839, the pipeline still fails. These are the errors:

```
=========================== short test summary info ============================
FAILED climada_petals/hazard/test/test_tc_rainfield.py::TestReader::test_cross_antimeridian - TypeError: get_close_centroids() missing 1 required positional argument: 'buffer_km'
FAILED climada_petals/hazard/test/test_tc_rainfield.py::TestReader::test_from_file_pass - TypeError: get_close_centroids() missing 1 required positional argument: 'buffer_km'
FAILED climada_petals/hazard/test/test_tc_rainfield.py::TestReader::test_set_one_pass - TypeError: get_close_centroids() missing 1 required positional argument: 'buffer_km'
FAILED climada_petals/hazard/test/test_tc_rainfield.py::TestReader::test_tcr - TypeError: get_close_centroids() missing 1 required positional argument: 'buffer_km'
FAILED climada_petals/hazard/test/test_tc_rainfield.py::TestReader::test_two_files_pass - TypeError: get_close_centroids() missing 1 required positional argument: 'buffer_km'
FAILED climada_petals/hazard/test/test_tc_rainfield.py::TestModel::test_rainfield_diff_time_steps - TypeError: get_close_centroids() missing 1 required positional argument: 'buffer_km'
FAILED climada_petals/hazard/test/test_tc_surge_bathtub.py::TestTCSurgeBathtub::test_cross_antimeridian - AssertionError: 1.3178962188473244 != 0.0
=========== 7 failed, 144 passed, 694 warnings in 170.62s (0:02:50) ============
```
I don't really understand how these come about because the `buffer_km` argument is given in these instances 🤔

**Comment by tovogt** [comment]
> I don't really understand how these come about because the `buffer_km` argument is given in these instances 🤔

This is exactly the kind of error that we get when working with the version of `get_close_centroids` before the changes in https://github.com/CLIMADA-project/climada_python/pull/839 because the number of positional arguments has changed. How often is Jenkins checking out new versions of the core develop branch when running unit tests for petals? Maybe it's only checking out once per day or so?

**Comment by peanutfun** [comment]
@emanuel-schmid, how often is the Core updated in the Petals pipeline?

**Comment by peanutfun** [comment]
Ah, I was not aware that this had already taken effect. Is there a way to parameterize this? So that, e.g., one may set the Core version in one of the Jenkins scripts to make sure that the particular branch works with the target version? We would just need something like
```
pushd climada_python
git pull
git checkout <tag/branch>  # Enter target branch here
pip install -e ./
popd
```

**Comment by emanuel-schmid** [comment]
This wouldn't be safe, unless we had a virtual environment for each branch. Having a persistent conda environment for each branch is not feasible given the limited space on the server. Having a temporary environment for each branch is not ideal because of the building costs. Maybe a _venv_ environment on top of the conda environment could be a solution or manipulating the PYTHONPATH. I'm going to look into these.

**Comment by peanutfun** [comment]
True, we would manipulate the persistent environment. It should not be long until we merge the Centroids update, so I think this is not urgent. I wanted to give the GitHub Actions for Petals a shot anyway, maybe I can solve it there. This way, we can keep the Jenkins pipeline as is.

**Pull request merged**
