### PR TITLE
TC surge from dynamic GeoClaw model runs

### PR DESCRIPTION
**Pull request by tovogt**
Due to the repository split, this PR is moved from https://github.com/CLIMADA-project/climada_python/pull/245.

This adds a new module `climada.hazard.tc_surge_geoclaw` that introduces a new Hazard class called `TCSurgeGeoClaw`. This new hazard models the storm surge impact from tropical cyclone tracks. Internally, the fluid dynamics solver [GeoClaw](http://www.clawpack.org/geoclaw) is used to simulate the storm surge dynamics. Please refer to the [tutorial notebook](https://github.com/CLIMADA-project/climada_petals/blob/feature/tc_surge_geoclaw/doc/tutorial/climada_hazard_TCSurgeGeoClaw.ipynb) for more information.

It's important to note that this functionality is not for the average user of CLIMADA: It requires a Fortran compiler, a non-trivial choice of input data as well as large computing power. The example of a single TC track in the tutorial notebook takes 3 hours to run even with 16 CPUs on a cluster. All this is mentioned in the code, docstrings and in the tutorial notebook.

Because of that, the usual unit tests for this module (`python -m unittest climada.hazard.test.test_tc_surge_geoclaw`) do not include non-trivial model runs. However, there is a non-trivial integration test (`python -m unittest climada.test.test_tc_surge_geoclaw`) that runs on a modern laptop computer in 1-2 hours.

### CODE REVIEW

**Comment by chahank** [comment]
Is this branch in the need of a review at some point?

**Comment by tovogt** [comment]
In principle yes, but there is no strict deadline and I don't know when I would have time to react to such a review.

**Comment by chahank** [comment]
@tovogt : is there a reason at the moment for keeping the pull request open? We can otherwise close it and re-open it when needed.

**Comment by tovogt** [comment]
Yes, I will reopen this, once I really have the time to resolve the conflicts with the develop branch and to react to reviews...

**Pull request closed without merging**
